# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46da7066caf4f0f23f8c0673b72900ac541609c8d5f67f91c73cbbb34b4f18c516ef107b2a4352b67c35bcc36f2498359398cb00a23caa628756ddc4855436f2

test:
  secret_key_base: 52a68879c191876dff95c6b89a4db97f94d3c6bd7bc196f9ea6ac11245f289fd1925c60d86bad85a02e483526547da26c09cff6e63c2e0cdf0a5a65df64b480d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
